apiVersion: data.fluid.io/v1alpha1
kind: ThinRuntimeProfile
metadata:
  name: curvine-profile
spec:
  fileSystemType: fuse
  fuse:
    image: ghcr.io/curvineio/curvine-fluid
    imageTag: latest
    imagePullPolicy: IfNotPresent
---
# Dataset definition
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: curvine-dataset
spec:
  mounts:
  - mountPoint: curvine:///data  # curvine://path format
    name: curvine
    options:
      master-endpoints: "127.0.0.1:8995"  # Replace with your Curvine master
  accessModes:
    - ReadOnlyMany
---
# ThinRuntime definition
apiVersion: data.fluid.io/v1alpha1
kind: ThinRuntime
metadata:
  name: curvine-dataset
spec:
  profileName: curvine-profile
